import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, CheckCircle, ImagePlus, Save, X } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useToast } from '@/context/ToastContext';
import { classificationService, type ClassificationBatchDetail, type ClassificationCatalog } from '@/services/classificationService';
import { uploadImages } from '@/utils/uploadImages';
import '@/styles/ops-shared.css';

const empty={fabricTypeId:'',garmentGroupId:'',clothingTypeId:'',genderId:'',targetUserId:'',sizeId:'',notes:'',answers:{} as Record<string,string>};
export default function ClassifyBatch(){
 const {batchId}=useParams(); const nav=useNavigate(); const toast=useToast();
 const [batch,setBatch]=useState<ClassificationBatchDetail|null>(null); const [catalog,setCatalog]=useState<ClassificationCatalog|null>(null); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false);
 const [images,setImages]=useState<{file:File;preview:string}[]>([]);
 const load=async()=>{if(!batchId)return; try{const [b,c]=await Promise.all([classificationService.getBatch(batchId),classificationService.getCatalog()]);setBatch(b);setCatalog(c);}catch{toast.error('Không tải được dữ liệu phân loại.');}};
 useEffect(()=>{load();},[batchId]);
 const allAnswered=useMemo(()=>catalog?.conditionQuestions.every(q=>form.answers[q.id])??false,[catalog,form.answers]);
 const set=(key:string,value:string)=>setForm(p=>({...p,[key]:value,...(key==='garmentGroupId'?{clothingTypeId:''}:{})}));
 const selectImages=(files:FileList|null)=>{if(!files)return;const selected=Array.from(files).filter(f=>f.type.startsWith('image/')).slice(0,5-images.length).map(file=>({file,preview:URL.createObjectURL(file)}));setImages(p=>[...p,...selected]);};
 const removeImage=(index:number)=>setImages(p=>{URL.revokeObjectURL(p[index].preview);return p.filter((_,i)=>i!==index);});
 const save=async()=>{if(!batchId||!catalog||!form.fabricTypeId||!form.garmentGroupId||!form.clothingTypeId||!form.genderId||!form.targetUserId||!form.sizeId||!allAnswered){toast.error('Vui lòng trả lời đầy đủ các bước.');return;} if(!images.length){toast.error('Vui lòng tải lên ít nhất một hình ảnh của item.');return;} setSaving(true);try{const imageUrls=await uploadImages(images.map(x=>x.file),'classified-items');const item=await classificationService.classifyItem(batchId,{...form,imageUrls,answers:catalog.conditionQuestions.map(q=>({questionId:q.id,answerId:form.answers[q.id]}))});toast.success(`Đã lưu ${item.itemCode} — Loại ${item.conditionGrade}.`);images.forEach(x=>URL.revokeObjectURL(x.preview));setImages([]);setForm(empty);await load();}catch(e:any){toast.error(e?.response?.data?.message||e?.message||'Không thể lưu kết quả.');}finally{setSaving(false);}};
 const complete=async()=>{if(!batchId)return;try{await classificationService.completeBatch(batchId);toast.success('Đã hoàn tất Intake Batch.');nav('/classification');}catch(e:any){toast.error(e?.response?.data?.message||'Không thể hoàn tất batch.');}};
 if(!batch||!catalog)return <div className="ops-page">Đang tải...</div>;
 return <div className="ops-page"><div className="ops-nav"><button className="ops-back" onClick={()=>nav('/classification')}><ChevronLeft size={16}/> Quay lại</button><div className="ops-title-row"><h1>{batch.batchCode}</h1><span className="ops-badge pending">{batch.status}</span></div></div>
 <div className="ops-panel glass"><span className="ops-panel-label">Tiến độ</span><h2>{batch.routeName}</h2><div className="ops-kv-grid"><div className="ops-kv"><span>Khối lượng</span><strong>{batch.totalWeight} kg</strong></div><div className="ops-kv"><span>Đơn quyên góp</span><strong>{batch.donationRequests}</strong></div><div className="ops-kv"><span>Item đã phân loại</span><strong>{batch.items.length}</strong></div></div></div>
 <div className="ops-form-grid two-col"><section className="ops-panel glass"><span className="ops-panel-label">Thuộc tính định danh</span><h2>Item mới #{batch.items.length+1}</h2>
 {[['Loại vải','fabricTypeId',catalog.fabricTypes],['Nhóm trang phục','garmentGroupId',catalog.garmentGroups],['Loại áo / quần','clothingTypeId',catalog.clothingTypes.filter(x=>x.parentId===form.garmentGroupId)],['Giới tính','genderId',catalog.genders],['Đối tượng','targetUserId',catalog.targetUsers],['Kích cỡ','sizeId',catalog.sizes]].map(([label,key,options]:any)=><div className="ops-field" key={key}><label>{label}</label><select value={(form as any)[key]} onChange={e=>set(key,e.target.value)}><option value="">-- Chọn --</option>{options.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>)}
 <div className="ops-field"><label>Hình ảnh item (bắt buộc, tối đa 5 ảnh)</label><label className="ops-image-picker"><ImagePlus size={22}/><span>Chụp hoặc chọn hình ảnh</span><small>{images.length}/5 ảnh</small><input type="file" accept="image/*" capture="environment" multiple disabled={images.length>=5||saving} onChange={e=>{selectImages(e.target.files);e.target.value='';}}/></label>{images.length>0&&<div className="ops-image-grid">{images.map((image,index)=><div className="ops-image-preview" key={image.preview}><img src={image.preview} alt={`Item ${index+1}`}/><button type="button" aria-label="Xóa ảnh" onClick={()=>removeImage(index)}><X size={14}/></button></div>)}</div>}</div>
 <div className="ops-field"><label>Ghi chú</label><textarea value={form.notes} onChange={e=>set('notes',e.target.value)}/></div></section>
 <section className="ops-panel glass"><span className="ops-panel-label">Đánh giá tình trạng A / B / C</span><h2>Ma trận chất lượng</h2>{catalog.conditionQuestions.map(q=><div className="ops-field" key={q.id}><label>{q.displayOrder}. {q.text}</label><div className="ops-item-list">{q.options.map(o=><button type="button" key={o.id} className={`ops-item-row ${form.answers[q.id]===o.id?'active':''}`} onClick={()=>setForm(p=>({...p,answers:{...p.answers,[q.id]:o.id}}))}><div className="ops-item-main"><strong>Nhãn {o.grade}</strong><span>{o.text}</span></div></button>)}</div></div>)}<div className="ops-actions"><button className="ops-btn ops-btn-primary ops-btn-block" disabled={saving} onClick={save}><Save size={16}/> {saving?'Đang lưu...':'Lưu item và phân loại tự động'}</button></div></section></div>
 <section className="ops-panel glass"><div className="ops-section-head"><h2>Item đã hoàn thành</h2><button className="ops-btn ops-btn-secondary" disabled={!batch.items.length} onClick={complete}><CheckCircle size={16}/> Hoàn tất batch</button></div><div className="ops-item-list">{batch.items.map(i=><div className="ops-item-row" key={i.id}>{i.imageUrls?.[0]&&<img className="ops-item-thumb" src={i.imageUrls[0]} alt={i.itemCode}/>}<div className="ops-item-main"><strong>{i.itemCode} · Loại {i.conditionGrade}</strong><span>{i.fabricType} · {i.clothingType} · {i.gender} · {i.targetUser} · {i.size}</span></div><span className="ops-badge done">{i.processingDirection}</span></div>)}{!batch.items.length&&<p>Chưa có item nào được phân loại.</p>}</div></section></div>;
}
