import { useEffect, useState } from 'react';
import { ArrowRightLeft, Boxes, Search, Send } from 'lucide-react';
import { useToast } from '@/context/ToastContext';
import { warehouseService, type StorageLocation, type WarehouseInventory } from '@/services/warehouseService';
import '@/styles/ops-shared.css';

export default function WarehouseInventoryPage(){
 const toast=useToast();const [items,setItems]=useState<WarehouseInventory[]>([]);const [search,setSearch]=useState('');const [selected,setSelected]=useState<WarehouseInventory|null>(null);const [mode,setMode]=useState<'issue'|'move'|null>(null);const [locations,setLocations]=useState<StorageLocation[]>([]);const [form,setForm]=useState({quantity:1,weightKg:1,reason:'Phân phối từ thiện',notes:'',destinationLocationId:''});
 const load=()=>warehouseService.inventory(search).then(setItems).catch(()=>toast.error('Không tải được tồn kho.'));
 useEffect(()=>{load();},[]);
 const open=async(item:WarehouseInventory,next:'issue'|'move')=>{setSelected(item);setMode(next);setForm(f=>({...f,quantity:Math.min(1,item.availableQuantity),weightKg:Math.min(1,item.availableWeightKg)}));if(next==='move'){const l=await warehouseService.locations(item.classifiedBatchId);setLocations(l.filter(x=>x.locationCode!==item.locationCode));setForm(f=>({...f,destinationLocationId:l.find(x=>x.locationCode!==item.locationCode)?.id||''}));}};
 const submit=async()=>{if(!selected||!mode)return;try{if(mode==='issue')await warehouseService.issue(selected.id,{quantity:form.quantity,weightKg:form.weightKg,reason:form.reason,notes:form.notes});else await warehouseService.move(selected.id,{destinationLocationId:form.destinationLocationId,reason:form.reason,notes:form.notes});toast.success(mode==='issue'?'Đã xuất kho và ghi transaction OUT.':'Đã điều chuyển và ghi transaction MOVE.');setMode(null);setSelected(null);load();}catch(e:any){toast.error(e?.response?.data?.message||'Không thực hiện được nghiệp vụ.');}};
 return <div className="ops-page"><header className="ops-pagehead"><div className="ops-pagehead-main"><span className="ops-pagehead-kicker">Stock Ledger</span><h1>Tồn kho theo SKU và vị trí</h1><p>Tồn khả dụng đã trừ phần giữ chỗ; mỗi SKU truy ngược được Classified Batch nguồn.</p></div></header>
 <section className="ops-panel glass"><div className="ops-field"><label>Tìm SKU, loại hàng hoặc mã vị trí</label><div style={{display:'flex',gap:8}}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button className="ops-btn ops-btn-secondary" onClick={load}><Search size={16}/>Tìm</button></div></div></section>
 <div className="ops-list" style={{marginTop:20}}>{items.map(item=><article className="ops-card" key={item.id}><div className="ops-card-top"><div><div className="ops-card-code">{item.sku}</div><div className="ops-card-meta"><span>{item.locationCode}</span><span>{item.areaName}</span><span>Nhãn {item.conditionGrade}</span></div></div><span className={`ops-badge ${item.status==='Available'?'done':'pending'}`}>{item.status}</span></div><h3>{item.clothingType} · {item.fabricType}</h3><div className="ops-kv-grid"><div className="ops-kv"><span>Khả dụng</span><strong>{item.availableQuantity} item</strong></div><div className="ops-kv"><span>Khối lượng khả dụng</span><strong>{item.availableWeightKg} kg</strong></div><div className="ops-kv"><span>Batch nguồn</span><strong>{item.batchCode}</strong></div><div className="ops-kv"><span>Phân loại</span><strong>{item.gender} · {item.targetUser} · {item.size}</strong></div></div><div className="ops-actions"><button className="ops-btn ops-btn-secondary" disabled={item.status!=='Available'} onClick={()=>open(item,'move')}><ArrowRightLeft size={15}/>Điều chuyển</button><button className="ops-btn ops-btn-primary" disabled={item.availableQuantity<=0} onClick={()=>open(item,'issue')}><Send size={15}/>Xuất kho</button></div></article>)}{!items.length&&<div className="ops-empty"><Boxes size={36}/><h4>Chưa có tồn kho</h4></div>}</div>
 {selected&&mode&&<div className="ops-modal-overlay" onMouseDown={()=>setMode(null)}><section className="ops-modal glass" onMouseDown={e=>e.stopPropagation()}><h2>{mode==='issue'?'Phiếu xuất kho':'Phiếu điều chuyển nội bộ'}</h2><p>{selected.sku} · {selected.locationCode}</p>{mode==='issue'?<><div className="ops-field"><label>Số lượng xuất</label><input type="number" min={1} max={selected.availableQuantity} value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></div><div className="ops-field"><label>Khối lượng xuất (kg)</label><input type="number" min=".01" max={selected.availableWeightKg} step=".01" value={form.weightKg} onChange={e=>setForm({...form,weightKg:Number(e.target.value)})}/></div></>:<div className="ops-field"><label>Vị trí đích</label><select value={form.destinationLocationId} onChange={e=>setForm({...form,destinationLocationId:e.target.value})}>{locations.map(l=><option value={l.id} key={l.id}>{l.locationCode} · còn {l.availableCapacityKg}kg</option>)}</select></div>}<div className="ops-field"><label>Lý do nghiệp vụ</label><input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div><div className="ops-field"><label>Ghi chú</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button className="ops-btn ops-btn-primary ops-btn-block" onClick={submit}>Xác nhận và ghi sổ</button></section></div>}
 </div>;
}
